on:
  workflow_dispatch: 

  schedule:
    - cron:  '0 17 * * *'
    
  push:
    branches: main

name: github_actions_example

jobs:
  test_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: always
          cache-version: 1
          packages: |
            any::flexdashboard
            any::aws.s3
            any::gt
            any::dplyr
            any::ggplot2
        
      - name: run script
        run: Rscript -e 'print("Hello R World!")' '
